# ---------------------------------------------------------------------------
# SSH key pairs, generated by Terraform (no pre-existing AWS key pair
# needed - same approach as the CR3_demo project).
#
# One key pair PER ROLE, so the bastion key cannot open internal hosts and
# an internal key leak doesn't expose the bastion. Keys are written to
# sshkeys_generated/ (gitignored, private keys mode 0600) and a ready-made
# ssh config is generated as ./sshcfg (see outputs.tf):
#
#   ssh -F sshcfg bastion
#   ssh -F sshcfg db1
#   ssh -F sshcfg ubuntu@<web-private-ip>   # via ProxyJump automatically
#
# NOTE: the private keys also live in Terraform state (tls_private_key
# stores its material there) - one more reason state must stay in the
# encrypted, access-controlled backend (see bootstrap/).
# ---------------------------------------------------------------------------

locals {
  ssh_roles = toset(["bastion", "web", "database", "monitoring"])

  ssh_key_dir = "${path.module}/sshkeys_generated"
  ssh_key_file = {
    for role in local.ssh_roles :
    role => "${local.ssh_key_dir}/${var.project_name}-${var.environment}-${role}"
  }
}

resource "tls_private_key" "ssh" {
  for_each = local.ssh_roles

  algorithm = "ED25519"
}

resource "local_file" "ssh_public" {
  for_each = local.ssh_roles

  content  = tls_private_key.ssh[each.key].public_key_openssh
  filename = "${local.ssh_key_file[each.key]}.pub"
}

resource "local_file" "ssh_private" {
  for_each = local.ssh_roles

  content         = tls_private_key.ssh[each.key].private_key_openssh
  filename        = local.ssh_key_file[each.key]
  file_permission = "0600"
}

resource "aws_key_pair" "role" {
  for_each = local.ssh_roles

  key_name   = "${var.project_name}-${var.environment}-${each.key}-kp"
  public_key = tls_private_key.ssh[each.key].public_key_openssh

  tags = {
    Environment = var.environment
    Role        = each.key
  }
}
